language: r

sudo: false

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: ETMmo3P7SZ04nYDaR87oEIfvkWtEpgs1BMovD1IvsHnLZMjp6vd9mKsV81ZBqLLaX0uFUEOKGI/Z0/9UO7hbscKUC30dNUCRMR7z7Btlg0IBFQc9Y979TPSyUxHyxUoQSoMynl8Qswhz46IgajCFu/QeyA4qRiAchQho+8u+1yZNgppyIXt7uAEXSgDUJ3j47jUPl8ic9yfllut/lLXua3wby4J9QyRBRCn9SnH0dkg2fiNgRcR9NDPilRJG/DOWE0w4SY4WPKleHxH4WsdYYpgtkChmMlTr6txw6Z6U8mucKpkj/eb+70yTdeterft3WEsW/MMqr0QkEN9v8+GXiNcrey7y25czuyZG+5/6MoCuemCk5KSgojXxvYzOLjxpCaFnuNMLXQO1KofvuMZ+oPX6Fo8CAHTS5HZSsln+9UviPQKipWWS1Q5rjYJAov5P1DmzZ18KGZakZetpxP6xqxTs+o64L1no4pV69EFgtdI+YL2ZeI2c3rbcja6+/PDL705//62wM6znrRoofoMmuxTQqcFQTc4agyEIRbeKRT2aP5XpMt6hliLe3MkVvBXxmt+zwMb3RFiMWM9O+6Mbxe5NJGrrdAOaNSa9tWrVYpp97Aj8XlmwLb2ZQmjQ4sWaSzc2/RFwi7fVVB4lbDBLO5kolYr2wuI9bvwkjNUddpo=
